apiVersion: apps/v1
kind: Deployment
metadata:
  name: kicksoccer-node
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kicksoccer-node
  template:
    metadata:
      labels:
        app: kicksoccer-node
    spec:
      containers:
        - name: kicksoccer-node
          image: rafaeltoky0/kicksoccer:0.0.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8332
              name: rpc
          command:
            - "kicksoccerd"
          args:
            - "-printtoconsole"
            - "-rpcallowip=0.0.0.0"
            - "-rpcbind=0.0.0.0"
            - "-rpcuser=dev"
            - "-rpcpassword=dev"
            - "-rpcport=8332"
            - "-testnet"
